### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by GXTX** [XboxDev/xbox-linux-busybox#1]
Currently the repo uses the `master` branch for Xbox specific changes, what I would like to see if possible is `master` be inline with upstream BusyBox (and other `xbox-linux-*` repos) and a branch specific to xbox-linux.

I plan to once this is finished PR a updated version of BusyBox.

**Comment by haxar** [comment]
This repo does not have any Xbox specific changes, other than including a custom config file & for `xbox-linux-initramfs` to comply with the license for including a `busybox` binary, which is built from this repo.

If you do submit a PR for the repo to be inline with upstream, I will have to update the binary in `xbox-linux-initramfs`.

**Comment by GXTX** [comment]
PR open for the update, I was hoping to have `master` just be a copy of upstream busybox but it doesn't really matter.

**Comment by JayFoxRox** [comment]
I'd suggest to rename our branch to "xbox" or "xbox-linux" but do not add another copy of upstream / master (because there wouldn't be any development on it, and it's easy enough to compare the base).

This is also how we handle it here (although our branch name is "nxdk" there):
- https://github.com/XboxDev/nxdk-pdclib
- https://github.com/XboxDev/nxdk-libcxx
- https://github.com/XboxDev/nxdk-sdl
- ...
